import type { Metadata } from "next";
import Image from 'next/image';
import styles from './scripts.module.css'

export const metadata: Metadata = {
    title: "Alma: Age-PRO - Scripts",
    description: "Generated by create next app",
  };

const ScriptsPage = () => {
    return (
        <div>Scripts</div>
    );
};

export default ScriptsPage;
