import type { Metadata } from "next";
import Image from 'next/image';
import styles from './press.module.css'

export const metadata: Metadata = {
    title: "Alma: Age-PRO - Press",
    description: "Generated by create next app",
  };

const Press = () => {
    return (
        <div>Press</div>
    );
};

export default Press;
