import type { Metadata } from "next";
import Image from 'next/image';
import styles from './regions.module.css'

export const metadata: Metadata = {
    title: "Alma: Age-PRO - Regions",
    description: "Generated by create next app",
  };

const Regions = () => {
    return (
        <div>Regions</div>
    );
};

export default Regions;
