import type { Metadata } from "next";
import Image from 'next/image';
import styles from './regions.module.css';

export const metadata: Metadata = {
    title: "Alma: Age-PRO - Regions",
    description: "Generated by create next app",
};

const RegionsData = {
    Ophiuchus: {
        info: 'Ophiuchus es una constelación ubicada cerca del ecuador celeste. Su nombre significa "portador de serpientes".',
        image: '/regions/ophiuchus.jpg',
        table: [
            { ID: 'Oph 1', fullname: 'SSTc2dJ162623.6-242439', RA: '16:26:23.571', Dec: '-24:24:40.102', distance: '-', SpT: 'K7', Class: 'FS', Teff: '3970', Lstar: '0.9', Av: '24', Mstar: '0.6', Macc: '-' },
            { ID: 'Oph 2', fullname: 'SSTc2dJ162703.6-242005', RA: '16:27:03.580', Dec: '-24:20:06.018', distance: '-', SpT: 'M1.5', Class: 'FS', Teff: '3560', Lstar: '0.4', Av: '20', Mstar: '0.4', Macc: '-' },
            { ID: 'Oph 3', fullname: 'SSTc2dJ162719.2-242844', RA: '16:27:19.196', Dec: ' -24:28:44.499', distance: '-', SpT: 'K7', Class: 'FS', Teff: '3970', Lstar: '0.9', Av: '26', Mstar: '0.6', Macc: '-' },
            { ID: 'Oph 4', fullname: 'SSTc2dJ162728.4-242721', RA: '16:27:28.436', Dec: '-24:27:21.790 ', distance: '-', SpT: 'K6.5', Class: 'FS', Teff: '3995', Lstar: '0.9', Av: '30', Mstar: '0.6', Macc: '-' },
            { ID: 'Oph 5', fullname: 'SSTc2dJ162737.2-244237', RA: '16:27:37.235 ', Dec: '-24:27:21.790 ', distance: '-', SpT: 'K9 ', Class: 'I', Teff: '3880', Lstar: '0.8', Av: '37', Mstar: '0.5', Macc: '-' },
            { ID: 'Oph 6', fullname: 'SSTc2dJ162738.9-244020', RA: '16:27:38.931', Dec: '-24:40:21.168 ', distance: '-', SpT: 'M2.5 ', Class: 'I', Teff: '3425', Lstar: '0.3', Av: '22', Mstar: '0.3', Macc: '-' },
            { ID: 'Oph 7', fullname: 'SSTc2dJ163135.6-240129', RA: '16:31:35.647', Dec: '-24:01:30.048 ', distance: '-', SpT: 'K6', Class: 'I', Teff: '4020', Lstar: '1', Av: '32', Mstar: '0.7', Macc: '-' },
            { ID: 'Oph 8', fullname: 'SSTc2d J162305.4-230257', RA: '16:23:05.416 ', Dec: '-23:02:57.553', distance: '-', SpT: 'M0.5', Class: 'I', Teff: '3700', Lstar: '0.5', Av: '7', Mstar: '0.4', Macc: '-' },
            { ID: 'Oph 9', fullname: 'SSTc2dJ162627.5-244153', RA: '16:26:27.538', Dec: '-24:41:53.527 ', distance: '-', SpT: 'M2.5 ', Class: 'FS', Teff: '3425', Lstar: '0.3', Av: '22', Mstar: '0.3', Macc: '-' },
            { ID: 'Oph 10', fullname: 'SSTc2dJ162718.4-243915', RA: '16:27:18.371', Dec: '24:39:15.325 ', distance: '-', SpT: 'M1', Class: 'I', Teff: '3630', Lstar: '0.5', Av: '27', Mstar: '0.4', Macc: '-' },
        ],
    },
    Lupus: {
        info: 'Lupus es una constelación del hemisferio sur. Su nombre significa "lobo" en latín.',
        image: '/regions/lupus.jpg',
        table: [
            { ID: 'Lupus 1', fullname: 'Sz65', RA: '15:39:27.753', Dec: '-34:46:17.577', distance: '153.47', SpT: 'K7', Class: 'II', Teff: '4060', Lstar: '0.869', Av: '0.6', Mstar: '0.61', Macc: '-9.48' },
            { ID: 'Lupus 2', fullname: 'Sz71', RA: '15:46:44.709', Dec: '-34:30:36.054', distance: '155.2', SpT: 'M1.5', Class: 'II', Teff: '3632', Lstar: '0.327', Av: '0.5', Mstar: '0.414', Macc: '-9.033' },
            { ID: 'Lupus 3', fullname: 'J16124373-3815031', RA: '16:12:43.736', Dec: '-38:15:03.471', distance: '159.85', SpT: 'M1', Class: 'II', Teff: '3705', Lstar: '0.39', Av: '0.8', Mstar: '0.47', Macc: '-9.084' },
            { ID: 'Lupus 4', fullname: 'Sz72', RA: '15:47:50.608', Dec: '-35:28:35.779', distance: '156.71', SpT: 'M2', Class: 'II', Teff: '3560', Lstar: '0.272', Av: '0.75', Mstar: '0.374', Macc: '-8.601' },
            { ID: 'Lupus 5', fullname: 'Sz77', RA: '15:51:46.941', Dec: '-35:56:44.531', distance: '155.25', SpT: 'K7', Class: 'II', Teff: '4060', Lstar: '0.593', Av: '0', Mstar: '0.67', Macc: '-8.69' },
            { ID: 'Lupus 6', fullname: 'J16085324-3914401', RA: '16:08:53.227', Dec: '-39:14:40.553', distance: '163', SpT: 'M3', Class: 'II', Teff: '3415', Lstar: '0.198', Av: '1.9', Mstar: '0.291', Macc: '-10.03' },
            { ID: 'Lupus 7', fullname: 'Sz131', RA: '16:00:49.414', Dec: '-41:30:04.263', distance: '160.62', SpT: 'M3', Class: 'II', Teff: '3415', Lstar: '0.15', Av: '1.3', Mstar: '0.301', Macc: '-9.171' },
            { ID: 'Lupus 8', fullname: 'Sz66', RA: '15:39:28.264', Dec: '-34:46:18.450', distance: '155.92', SpT: 'M3', Class: 'II', Teff: '3415', Lstar: '0.216', Av: '1', Mstar: '0.291', Macc: '-8.508' },
            { ID: 'Lupus 9', fullname: 'Sz95', RA: '16:07:52.293', Dec: '-38:58:06.446', distance: '160.47', SpT: 'M3', Class: 'II', Teff: '3415', Lstar: '0.267', Av: '0.8', Mstar: '0.291', Macc: '-9.381' },
            { ID: 'Lupus 10', fullname: 'V1094Sco', RA: '16:08:36.160', Dec: '-39:23:02.879', distance: '158', SpT: 'K6', Class: 'II', Teff: '4205', Lstar: '1.21', Av: '1.7', Mstar: '0.64', Macc: '-7.88' },
        ],
    },
    UpperScorpius: {
        info: 'UppSco es una región de formación estelar en la constelación de Scorpius.',
        image: '/regions/UpperSco.jpg',
        table: [
            { ID: 'Upper Sco 1', fullname: 'J16120668-3010270', RA: '16 12 06.664505', Dec: '−30 10 27.61789', distance: '131.9', SpT: 'M0', Class: 'Full', Teff: '3700', Lstar: '0.21', Av: '0.056', Mstar: '0.55', Macc: '3.98E-10' },
            { ID: 'Upper Sco 2', fullname: 'J16054540-2023088', RA: '16 05 45.379300', Dec: '-20 23 09.33099', distance: '137.58', SpT: 'M2', Class: 'Full', Teff: '3020', Lstar: '0.07', Av: '0.262', Mstar: '0.2', Macc: '3.58E-10' },
            { ID: 'Upper Sco 3', fullname: 'J16020757-2257467', RA: '16 02 07.556045', Dec: '-22 57 47.42497', distance: '139.62', SpT: 'M2', Class: 'Full', Teff: '3490', Lstar: '0.15', Av: '0.523', Mstar: '0.44', Macc: '3.58E-10' },
            { ID: 'Upper Sco 4', fullname: 'J16111742-1918285', RA: '16 11 17.406', Dec: '-19 18 29.231', distance: '136.87', SpT: 'M0.25', Class: 'Full', Teff: '3735', Lstar: '0.35', Av: '0.896', Mstar: '0.672', Macc: '-' },
            { ID: 'Upper Sco 5', fullname: 'J16145026-2332397', RA: '16 14 50.249254', Dec: '-23 32 40.23887', distance: '143.99', SpT: 'M3', Class: 'Full', Teff: '3360', Lstar: '0.11', Av: '1.445', Mstar: '-', Macc: '-' },
            { ID: 'Upper Sco 6', fullname: 'J16163345-2521505 ', RA: '16 16 33.429811', Dec: '-25 21 51.16379', distance: '158.4', SpT: 'M0', Class: 'Full', Teff: '3700', Lstar: '0.18', Av: '1.069', Mstar: '0.56', Macc: '1.23E-11' },
            { ID: 'Upper Sco 7', fullname: 'J16202863-2442087', RA: '16 20 28.622255', Dec: '-24 42 09.17464', distance: '152.7', SpT: 'M2', Class: 'Full', Teff: '3490', Lstar: '0.23', Av: '1.71', Mstar: '-', Macc: '-' },
            { ID: 'Upper Sco 8', fullname: 'J16221532-2511349', RA: '16 22 15.324556', Dec: '-25 11 35.67277', distance: '138.99', SpT: 'M3', Class: 'Full', Teff: '3360', Lstar: '0.14', Av: '1.903', Mstar: '-', Macc: '-' },
            { ID: 'Upper Sco 9', fullname: 'J16082324-1930009', RA: '16 08 23.2470', Dec: '-19 30 00.980', distance: '136.96', SpT: 'M0', Class: 'Full', Teff: '3880', Lstar: '0.24', Av: '1.156', Mstar: '0.61', Macc: '7.90E-10' },
            { ID: 'Upper Sco 10', fullname: 'J16090075-1908526', RA: '16 09 00.739511', Dec: '-19 08 53.28490', distance: '136.94', SpT: 'M0', Class: 'Full', Teff: '3630', Lstar: '0.35', Av: '0.888', Mstar: '0.6', Macc: '1.74E-09' },
        ],
    },
};

const Regions = () => {
    return (
        <div className={styles.container}>
            <div className={styles.info}>
                <h1 className={styles.title}>Regions</h1>
                <hr className={styles.line} />
                {Object.keys(RegionsData).map((region) => (
                    <div key={region} className={styles.region}>
                        <h2 className={styles.regionTitle}>{region}</h2>
                        <div className={styles.regionDescription}>
                            <p className={styles.regionInfo}>{RegionsData[region as keyof typeof RegionsData].info}</p>
                            <Image
                                src={RegionsData[region as keyof typeof RegionsData].image}
                                alt={region}
                                width={300}
                                height={300}
                                className={styles.regionImage}
                            />
                        </div>
                        <div className={styles.tableContainer}>
                            <table className={styles.table}>
                                <thead>
                                    <tr>
                                        <th className={styles.th}>ID</th>
                                        <th className={styles.th}>Full name</th>
                                        <th className={styles.th}>RA</th>
                                        <th className={styles.th}>Dec</th>
                                        <th className={styles.th}>Distance</th>
                                        <th className={styles.th}>SpT</th>
                                        <th className={styles.th}>Class</th>
                                        <th className={styles.th}>T<sub>eff</sub></th>
                                        <th className={styles.th}>L<sub>star</sub></th>
                                        <th className={styles.th}>Av</th>
                                        <th className={styles.th}>M<sub>star</sub></th>
                                        <th className={styles.th}>M<sub>acc</sub></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {RegionsData[region as keyof typeof RegionsData].table.map((row, index) => (
                                        <tr key={index} className={index % 2 === 0 ? styles.evenRow : ''}>
                                            {Object.values(row).map((value, i) => (
                                                <td key={i} className={styles.td}>{value}</td>
                                            ))}
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default Regions;
