import type { Metadata } from "next";
import Image from 'next/image';
import styles from './data.module.css'

export const metadata: Metadata = {
    title: "Alma: Age-PRO - Data",
    description: "Generated by create next app",
  };

const DataPage = () => {
    return (
        <div>Data</div>
    );
};

export default DataPage;