import type { Metadata } from "next";
import Image from 'next/image';
import styles from './disks.module.css'

export const metadata: Metadata = {
    title: "Alma: Age-PRO - Disks",
    description: "Generated by create next app",
  };

const Disks = () => {
    return (
        <div>Disks</div>
    );
};

export default Disks;
