import type { Metadata } from "next";
import Image from 'next/image';
import styles from './team.module.css';
import { Collapse } from "antd";
import CollapsePanel from "antd/es/collapse/CollapsePanel";
import teamMembers from './data/teamMembers';

export const metadata: Metadata = {
    title: "Alma: Age-PRO - Team",
    description: "Generated by create next app",
  };


const Team = () => {
    return (
        <div className={styles.teamContainer}>
            <div className={styles.teamDescription}>
                <h1>Our Team</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                <h2>Institutions & Funding</h2>
                <Image src="/institutions/uchilelogo.jpg" alt="Institution 1" width={300} height={120} />
                <Image src="/institutions/ulondonlogo.png" alt="Institution 2" width={300} height={140} />
                <Image src="/institutions/uarizonalogo.png" alt="Institution 3" width={280} height={160} />
            </div>
            <div className={styles.memberGrid}>
                {teamMembers.map(member => (
                    <Collapse key={member.fullName}>
                        <CollapsePanel
                            header={
                                <div className={styles.collapseCard}>
                                    <Image src="/team/anibal.jpg"
                                        alt={member.fullName}
                                        width={170}
                                        height={170}
                                        className={styles.memberImage}
                                    />
                                    <div className={styles.memberName}>{member.fullName}</div>
                                    <div className={styles.memberName}>{member.role}</div>
                                    <div className={styles.memberRole}>{member.institution}</div>
                                </div>
                            }
                            key={member.fullName}
                            showArrow={false}
                        >
                            <div className={styles.memberInfo}>
                                {member.cityCountry !== "nan" && <p><strong>City, Country:</strong> {member.cityCountry}</p>}
                                {member.team !== "nan" && <p><strong>Team:</strong> {member.team}</p>}
                                {member.personalWebsite !== "nan" && <p><strong>Personal Website:</strong> <a href={member.personalWebsite}>{member.personalWebsite}</a></p>}
                                {member.email !== "nan" && <p><strong>Email:</strong> <a href={`mailto:${member.email}`}>{member.email}</a></p>}
                                {member.expertise !== "nan" && <p><strong>Expertise:</strong> {member.expertise}</p>}
                            </div>
                        </CollapsePanel>
                    </Collapse>
                ))}
            </div>
        </div>
    );
};

export default Team;