import type { Metadata } from "next";
import Image from 'next/image';
import styles from './team.module.css'

export const metadata: Metadata = {
    title: "Alma: Age-PRO - Team",
    description: "Generated by create next app",
  };

const Team = () => {
    return (
        <div>Team</div>
    );
};

export default Team;