import type { Metadata } from "next";
import Image from 'next/image';
import styles from './publications.module.css'

export const metadata: Metadata = {
    title: "Alma: Age-PRO - Publications",
    description: "Generated by create next app",
  };

const Publications = () => {
    return (
        <div>Publications</div>
    );
};

export default Publications;
